# Generated by Django 4.2.1 on 2023-09-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
