# Generated by Django 4.2.1 on 2023-09-06 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
