# Generated by Django 4.2.1 on 2023-09-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format: {'tax_type': {'tax_percentage': 'tax_amount'}}", null=True),
        ),
    ]
