# Generated by Django 4.2.1 on 2023-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_tax',
            field=models.FloatField(null=True),
        ),
    ]
